### PR TITLE
Support for release builds and benchmarks

### PR DESCRIPTION
**Pull request by ebkalderon**
This pull request adds a release build target and a "cargo bench" option. The build targets' order of appearance was also changed into alphabetical order.

### CODE REVIEW

**Comment by colin-kiegel** [comment]
cool :-)

My only concern would be, that `bench` is not yet stabilized..

**Comment by ebkalderon** [comment]
Agreed, but it's still a useful feature that I use often, and it works well from within the `atom-build` panel. Would you still prefer it be removed?

**Comment by colin-kiegel** [comment]
+1 from me, but I'm not the maintainer ;)

**Comment by ebkalderon** [comment]
Thanks. @noseglid, any thoughts?

**Comment by noseglid** [comment]
Looks good! I'll merge it! Thanks for this!

**Pull request merged**
