### PR TITLE
Readme improvement

### PR DESCRIPTION
**Pull request by alygin**
I've added a short description of the features provided by the package and recorded a screencast that shows some of them. A screencast can be moved to https://github.com/AtomBuild if needed, but it must be done by someone with enough permissions. As far as I understand, it cannot be done by a PR.

### CODE REVIEW

**Comment by colin-kiegel** [comment]
Yes, I think you can put it in the pull request - just put it somewhere in the repository and use a relative path in the markdown.

Very nice screencast by the way. :-)

PS: I would suggest changing the title to something like "Cargo (Rust) integration for Atom"

**Comment by alygin** [comment]
I checked the screencast in Atom Build and found that it's placed under the url https://noseglid.github.io/build.gif which is outside of the repository, so I decided that this one must be somewhere in https://atombuild.github.io/. I also checked some other repositories that use screencasts in readme (linter and atom-beautify), they use clouds.

I also am not familiar with all the nuances of the final package build process. It may exclude the screencast from the package leaving the relative link broken. If it won't exclude the file, it still might be undesirable to put a couple of megabytes into the package. So, I decided to use a safe approach :)

I agree that the title "Cargo (Rust) integration for Atom" would work better. If nobody objects, I can change it in this PR.

**Comment by noseglid** [comment]
There's a problem with having them in the repository. It will not be displayed correctly on the README on atom.io (but github README works fine). That's why I put it somewhere else.

Wasn't there a new feature released recently allowing to put stuff in like a `/docs` folder?

**Comment by alygin** [comment]
I can't find an issue or a PR on adding support for `/docs` folder in Atom. The [official Atom manual](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#package-generator) also tells nothing about it.

There's one more possibility: If I add the file to a comment, GitHub will save it to https://cloud.github.com/ with a persistent url. Such approach is used by some repositories ([atom-beautify](https://github.com/Glavin001/atom-beautify), for instance).

**Comment by colin-kiegel** [comment]
I think you could also put it in the repo (e.g. docs folder) and use an absolute path like this one
https://raw.githubusercontent.com/AtomBuild/atom-build-cargo/master/LICENSE.md

However this will break if things change in the master branch and old readmes still point to old files

**Comment by alygin** [comment]
It's possible to make a link to the version of a file in a particular commit, so old readmes won't be a problem. But there will be another issue -- it will always take two commits to update the screencast (one for the screencast to extract its link, another for the readme with the fixed link). And one will always have to remember to do that.

I'm also concerned about building the final package. If the building script will include the screencast into the package while we use an absolute url, it will be an unpleasant waste of space.

Given all that, I think https://cloud.github.com/ is a bit better than other options at hand:
- It's on github
- Every file version has a unique persistent url that doesn't require a separate commit
- It doesn't make the package heavier

**Comment by alygin** [comment]
So, what will be the final verdicts on the screencast location and on the package title? @noseglid, @oli-obk?

**Comment by noseglid** [comment]
Sounds good to me. I've never used cloud.github.com so not sure if anything needs to be setup?

**Comment by alygin** [comment]
Perfect. No setup needed, I'll just add the file to this comment and use its link.
And what about changing the title to "Cargo (Rust) integration for Atom"?

zk2icsz7c6

**Comment by oli-obk** [comment]
Sorry about taking so long :) I was on vacation.

Great improvements

**Comment by alygin** [comment]
Thanks for merging!

Unfortunately, nobody answered about the title, so I left it untouched in this PR. What do you think on changing it to "Cargo (Rust) integration for Atom"?

**Comment by oli-obk** [comment]
I don't have much of an opinion as long as it contains "atom" and one of "cargo"/"rust".

since 2/N people want the new name, I'll change it and we'll have it in the next publish, whenever that happens :)

**Pull request merged**
